
--
-- Name: marketplace; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA marketplace;


--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA marketplace;


--
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: brands; Type: TABLE; Schema: marketplace; Owner: -
--

CREATE TABLE marketplace.brands (
    id bigint NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: brands_id_seq; Type: SEQUENCE; Schema: marketplace; Owner: -
--

ALTER TABLE marketplace.brands ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME marketplace.brands_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conditions; Type: TABLE; Schema: marketplace; Owner: -
--

CREATE TABLE marketplace.conditions (
    code text NOT NULL,
    label text NOT NULL
);


--
-- Name: listing_images; Type: TABLE; Schema: marketplace; Owner: -
--

CREATE TABLE marketplace.listing_images (
    id bigint NOT NULL,
    listing_id bigint NOT NULL,
    image_url text NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: listing_images_id_seq; Type: SEQUENCE; Schema: marketplace; Owner: -
--

ALTER TABLE marketplace.listing_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME marketplace.listing_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: listing_product_matches; Type: TABLE; Schema: marketplace; Owner: -
--

CREATE TABLE marketplace.listing_product_matches (
    listing_id bigint NOT NULL,
    product_id bigint NOT NULL,
    product_sku_id bigint NOT NULL,
    method text NOT NULL,
    score numeric(5,4) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT listing_product_matches_score_check CHECK (((score >= (0)::numeric) AND (score <= (1)::numeric)))
);


--
-- Name: listing_reads; Type: TABLE; Schema: marketplace; Owner: -
--

CREATE TABLE marketplace.listing_reads (
    id bigint NOT NULL,
    listing_id bigint NOT NULL,
    user_id bigint,
    first_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    last_opened_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: listing_reads_id_seq; Type: SEQUENCE; Schema: marketplace; Owner: -
--

ALTER TABLE marketplace.listing_reads ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME marketplace.listing_reads_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: listings; Type: TABLE; Schema: marketplace; Owner: -
--

CREATE TABLE marketplace.listings (
    id bigint NOT NULL,
    source_id bigint NOT NULL,
    external_id text NOT NULL,
    url text NOT NULL,
    title text NOT NULL,
    description text,
    price_cents bigint NOT NULL,
    currency text DEFAULT 'EUR'::text NOT NULL,
    condition_code text,
    has_shipping boolean DEFAULT false NOT NULL,
    shipping_cost_cents bigint,
    seller_id bigint,
    location_id bigint,
    published_at timestamp with time zone,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    raw_payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT listings_price_cents_check CHECK ((price_cents >= 0)),
    CONSTRAINT listings_shipping_cost_cents_check CHECK (((shipping_cost_cents IS NULL) OR (shipping_cost_cents >= 0)))
);


--
-- Name: listings_id_seq; Type: SEQUENCE; Schema: marketplace; Owner: -
--

ALTER TABLE marketplace.listings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME marketplace.listings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: locations; Type: TABLE; Schema: marketplace; Owner: -
--

CREATE TABLE marketplace.locations (
    id bigint NOT NULL,
    label text NOT NULL,
    country_code text DEFAULT 'FR'::text NOT NULL,
    lat double precision,
    lon double precision,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: locations_id_seq; Type: SEQUENCE; Schema: marketplace; Owner: -
--

ALTER TABLE marketplace.locations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME marketplace.locations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: marketplace; Owner: -
--

CREATE TABLE marketplace.products (
    id bigint NOT NULL,
    brand_id bigint NOT NULL,
    taxon_id bigint NOT NULL,
    model_name text NOT NULL,
    variant_name text,
    release_year integer,
    attributes jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: products_id_seq; Type: SEQUENCE; Schema: marketplace; Owner: -
--

ALTER TABLE marketplace.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME marketplace.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sellers; Type: TABLE; Schema: marketplace; Owner: -
--

CREATE TABLE marketplace.sellers (
    id bigint NOT NULL,
    source_id bigint NOT NULL,
    external_id text NOT NULL,
    display_name text NOT NULL,
    rating numeric(3,2),
    profile_url text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: sellers_id_seq; Type: SEQUENCE; Schema: marketplace; Owner: -
--

ALTER TABLE marketplace.sellers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME marketplace.sellers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sources; Type: TABLE; Schema: marketplace; Owner: -
--

CREATE TABLE marketplace.sources (
    id bigint NOT NULL,
    name text NOT NULL,
    base_url text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: sources_id_seq; Type: SEQUENCE; Schema: marketplace; Owner: -
--

ALTER TABLE marketplace.sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME marketplace.sources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: taxons; Type: TABLE; Schema: marketplace; Owner: -
--

CREATE TABLE marketplace.taxons (
    id bigint NOT NULL,
    parent_id bigint,
    name text NOT NULL,
    slug text NOT NULL,
    path text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: taxons_id_seq; Type: SEQUENCE; Schema: marketplace; Owner: -
--

ALTER TABLE marketplace.taxons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME marketplace.taxons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brands brands_name_key; Type: CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.brands
    ADD CONSTRAINT brands_name_key UNIQUE (name);


--
-- Name: brands brands_pkey; Type: CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.brands
    ADD CONSTRAINT brands_pkey PRIMARY KEY (id);


--
-- Name: conditions conditions_pkey; Type: CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.conditions
    ADD CONSTRAINT conditions_pkey PRIMARY KEY (code);


--
-- Name: listing_images listing_images_pkey; Type: CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.listing_images
    ADD CONSTRAINT listing_images_pkey PRIMARY KEY (id);


--
-- Name: listing_product_matches listing_product_matches_pkey; Type: CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.listing_product_matches
    ADD CONSTRAINT listing_product_matches_pkey PRIMARY KEY (listing_id, product_id, product_sku_id);


--
-- Name: listing_reads listing_reads_pkey; Type: CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.listing_reads
    ADD CONSTRAINT listing_reads_pkey PRIMARY KEY (id);


--
-- Name: listings listings_pkey; Type: CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.listings
    ADD CONSTRAINT listings_pkey PRIMARY KEY (id);


--
-- Name: locations locations_pkey; Type: CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.locations
    ADD CONSTRAINT locations_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: sellers sellers_pkey; Type: CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.sellers
    ADD CONSTRAINT sellers_pkey PRIMARY KEY (id);


--
-- Name: sources sources_name_key; Type: CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.sources
    ADD CONSTRAINT sources_name_key UNIQUE (name);


--
-- Name: sources sources_pkey; Type: CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.sources
    ADD CONSTRAINT sources_pkey PRIMARY KEY (id);


--
-- Name: taxons taxons_pkey; Type: CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.taxons
    ADD CONSTRAINT taxons_pkey PRIMARY KEY (id);


--
-- Name: listing_reads uq_listing_reads; Type: CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.listing_reads
    ADD CONSTRAINT uq_listing_reads UNIQUE (listing_id, user_id);


--
-- Name: listings uq_listings_source_external; Type: CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.listings
    ADD CONSTRAINT uq_listings_source_external UNIQUE (source_id, external_id);


--
-- Name: products uq_products_brand_taxon_model_variant; Type: CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.products
    ADD CONSTRAINT uq_products_brand_taxon_model_variant UNIQUE (brand_id, taxon_id, model_name, variant_name);


--
-- Name: sellers uq_sellers_source_external; Type: CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.sellers
    ADD CONSTRAINT uq_sellers_source_external UNIQUE (source_id, external_id);


--
-- Name: taxons uq_taxons_path; Type: CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.taxons
    ADD CONSTRAINT uq_taxons_path UNIQUE (path);


--
-- Name: taxons uq_taxons_slug; Type: CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.taxons
    ADD CONSTRAINT uq_taxons_slug UNIQUE (slug);


--
-- Name: idx_listing_images_listing; Type: INDEX; Schema: marketplace; Owner: -
--

CREATE INDEX idx_listing_images_listing ON marketplace.listing_images USING btree (listing_id);


--
-- Name: idx_listing_reads_listing; Type: INDEX; Schema: marketplace; Owner: -
--

CREATE INDEX idx_listing_reads_listing ON marketplace.listing_reads USING btree (listing_id);


--
-- Name: idx_listings_location; Type: INDEX; Schema: marketplace; Owner: -
--

CREATE INDEX idx_listings_location ON marketplace.listings USING btree (location_id);


--
-- Name: idx_listings_price; Type: INDEX; Schema: marketplace; Owner: -
--

CREATE INDEX idx_listings_price ON marketplace.listings USING btree (price_cents);


--
-- Name: idx_listings_source_fetched; Type: INDEX; Schema: marketplace; Owner: -
--

CREATE INDEX idx_listings_source_fetched ON marketplace.listings USING btree (source_id, fetched_at DESC);


--
-- Name: idx_lpm_listing; Type: INDEX; Schema: marketplace; Owner: -
--

CREATE INDEX idx_lpm_listing ON marketplace.listing_product_matches USING btree (listing_id);


--
-- Name: idx_lpm_product_score; Type: INDEX; Schema: marketplace; Owner: -
--

CREATE INDEX idx_lpm_product_score ON marketplace.listing_product_matches USING btree (product_id, score DESC);


--
-- Name: idx_products_attributes; Type: INDEX; Schema: marketplace; Owner: -
--

CREATE INDEX idx_products_attributes ON marketplace.products USING gin (attributes);


--
-- Name: idx_products_brand_taxon; Type: INDEX; Schema: marketplace; Owner: -
--

CREATE INDEX idx_products_brand_taxon ON marketplace.products USING btree (brand_id, taxon_id);


--
-- Name: idx_sellers_source; Type: INDEX; Schema: marketplace; Owner: -
--

CREATE INDEX idx_sellers_source ON marketplace.sellers USING btree (source_id);


--
-- Name: idx_taxons_parent; Type: INDEX; Schema: marketplace; Owner: -
--

CREATE INDEX idx_taxons_parent ON marketplace.taxons USING btree (parent_id);


--
-- Name: listing_images listing_images_listing_id_fkey; Type: FK CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.listing_images
    ADD CONSTRAINT listing_images_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES marketplace.listings(id) ON DELETE CASCADE;


--
-- Name: listing_product_matches listing_product_matches_listing_id_fkey; Type: FK CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.listing_product_matches
    ADD CONSTRAINT listing_product_matches_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES marketplace.listings(id) ON DELETE CASCADE;


--
-- Name: listing_product_matches listing_product_matches_product_id_fkey; Type: FK CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.listing_product_matches
    ADD CONSTRAINT listing_product_matches_product_id_fkey FOREIGN KEY (product_id) REFERENCES marketplace.products(id) ON DELETE RESTRICT;


--
-- Name: listing_reads listing_reads_listing_id_fkey; Type: FK CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.listing_reads
    ADD CONSTRAINT listing_reads_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES marketplace.listings(id) ON DELETE CASCADE;


--
-- Name: listings listings_condition_code_fkey; Type: FK CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.listings
    ADD CONSTRAINT listings_condition_code_fkey FOREIGN KEY (condition_code) REFERENCES marketplace.conditions(code) ON DELETE SET NULL;


--
-- Name: listings listings_location_id_fkey; Type: FK CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.listings
    ADD CONSTRAINT listings_location_id_fkey FOREIGN KEY (location_id) REFERENCES marketplace.locations(id) ON DELETE SET NULL;


--
-- Name: listings listings_seller_id_fkey; Type: FK CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.listings
    ADD CONSTRAINT listings_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES marketplace.sellers(id) ON DELETE SET NULL;


--
-- Name: listings listings_source_id_fkey; Type: FK CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.listings
    ADD CONSTRAINT listings_source_id_fkey FOREIGN KEY (source_id) REFERENCES marketplace.sources(id) ON DELETE RESTRICT;


--
-- Name: products products_brand_id_fkey; Type: FK CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.products
    ADD CONSTRAINT products_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES marketplace.brands(id) ON DELETE RESTRICT;


--
-- Name: products products_taxon_id_fkey; Type: FK CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.products
    ADD CONSTRAINT products_taxon_id_fkey FOREIGN KEY (taxon_id) REFERENCES marketplace.taxons(id) ON DELETE RESTRICT;


--
-- Name: sellers sellers_source_id_fkey; Type: FK CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.sellers
    ADD CONSTRAINT sellers_source_id_fkey FOREIGN KEY (source_id) REFERENCES marketplace.sources(id) ON DELETE RESTRICT;


--
-- Name: taxons taxons_parent_id_fkey; Type: FK CONSTRAINT; Schema: marketplace; Owner: -
--

ALTER TABLE ONLY marketplace.taxons
    ADD CONSTRAINT taxons_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES marketplace.taxons(id) ON DELETE SET NULL;

